name: Check locale files

# read-only repo token
# no access to secrets
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  pull_request:

jobs:
  locale-updater:
    if: github.repository == 'dpgraham4401/djangorestframework-simplejwt'
    name: Locale updater
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Checkout PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr checkout ${{ github.event.pull_request.number }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        # Note: do not cache dependencies to prevent cache poisoned

    - name: Install dependencies
      run: |
        sudo apt-get install -y gettext 
        python -m pip install --upgrade pip wheel setuptools
        pip install -e .[dev]

    - name: Run locale Update Script
      working-directory: rest_framework_simplejwt
      run: |
        python ../scripts/i18n_updater.py

    - name: Save PR number
      run: |
        mkdir -p ./pr
        echo "${{ github.event.number }}" > ./pr/NR

    - name: Upload PR number
      uses: actions/upload-artifact@v2
      with:
        name: pr
        path: ./pr

#    - name: update Pull Request
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      run: |
#        git config --global user.name 'github-actions[bot]'
#        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
#        git add rest_framework_simplejwt/locale/**
#        git commit -m "Update locale files"
#        git push
