name: Locale Updater

on:
  pull_request:

jobs:
  locale-updater:
    if: github.repository == 'dpgraham4401/django-rest-framework-simplejwt'
    name: Locale updater
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:

    - name: Checkout PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr checkout ${{ github.event.pull_request.number }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        sudo apt-get install -y gettext 
        python -m pip install --upgrade pip wheel setuptools
        pip install -e .[dev]

    - name: Run locale Update Script
      working-directory: rest_framework_simplejwt
      run: |
        python ../scripts/i18n_updater.py

    - name: update Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add rest_framework_simplejwt/locale/**
        git commit -m "Update locale files"
        git push
